import os

def create_bi_structure():
    base_folder = "Business_Intelligence_Dashboard"
    
    # Struktur folder sesuai blueprint
    folders = [
        "Excel",
        "PDF",
        "CSV",
        "Dashboard Image",
        "Company Profile",
        "Catalog",
        "Pricelist",
        "Documentation"
    ]
    
    print(f"Menginisialisasi arsitektur folder {base_folder}...")
    
    # Membuat direktori
    for folder in folders:
        path = os.path.join(base_folder, folder)
        os.makedirs(path, exist_ok=True)
        print(f"Berhasil membuat direktori: /{path}")

    # Membuat README.md sebagai dokumentasi sistem
    readme_content = """# Business Intelligence Supplier Database Indonesia

## Visi Sistem
Sistem ini dirancang untuk mencapai skalabilitas hingga:
- 1.000.000 Supplier
- 500.000 Brand
- 100.000 Produk

## Standard Operation Procedure (SOP) Input Data
1. **No Fictional Data**: Seluruh data HARUS dapat diverifikasi.
2. **Naming Convention**: Gunakan format SUP000001, BRD000001, PRD000001.
3. **Validasi**: Perbarui 'Supplier Trust Score' dan 'Investment Score' setelah setiap negosiasi.

## Struktur Direktori
- `/Excel/`: Berisi Master Workbook `Business Intelligence Dashboard.xlsx`
- `/CSV/`: Backup raw data dan import batch.
- `/Company Profile/`, `/Catalog/`, `/Pricelist/`: File vendor.
- `/PDF/`, `/Dashboard Image/`: Export report harian/bulanan.

---
*Generated by Business Intelligence Consulting Team*
"""
    
    readme_path = os.path.join(base_folder, "README.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(readme_content)
    
    print("\n[SUCCESS] Struktur folder siap digunakan!")
    print("Silakan pindahkan file Business Intelligence Dashboard.xlsx ke dalam folder /Excel/")

if __name__ == "__main__":
    create_bi_structure()
